version: '3.4'

services:
  database:
    image: '${REGISTRY_NAME}mongo:5.0.3-focal'
    volumes:
      - iitdconnectdb:/data/db
    networks:
      - 'internal'
    restart: 'unless-stopped'
  dashboard:
    build: .
    image: '${REGISTRY_NAME}devclubiitd/iitdconnect:0.1'
    volumes:
      - public_media:/code/media
      - protected_media:/code/protected
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:${PORT}']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: 'unless-stopped'
    ports:
      - ${PORT}
    networks:
      - 'internal'
      - 'reverseproxy'
    env_file:
      - ./.env
    environment:
      - DB_URL
      - PORT
    depends_on:
      - database

  nginx:
    image: '${REGISTRY_NAME}devclubiitd/iitdconnect-nginx:0.1'
    build: ./nginx
    volumes:
      - public_media:/code/media
      - protected_media:/code/protected
    ports:
      - 80
    depends_on:
      - dashboard
    networks:
      - 'reverseproxy'
      - 'internal'
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    restart: always

volumes:
  iitdconnectdb:
  public_media:
  protected_media:

networks:
  reverseproxy:
    external:
      name: 'reverseproxy'
  internal:
